export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const CHECK = "CHECK";
export const CHECK_SUCCESS = "CHECK_SUCCESS";
export const CHECK_FAILURE = "CHECK_FAILURE";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const OUT = "OUT";
export const OUT_SUCCESS = "OUT_SUCCESS";


export const UPLOAD = "UPLOAD";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const POST = "POST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";

export const LIST = "LIST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";

export const LIST_ADD = "LIST_ADD";
export const LIST_ADD_SUCCESS = "LIST_ADD_SUCCESS";
export const LIST_ADD_FAILURE = "LIST_ADD_FAILURE";

export const DETAIL = "DETAIL";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAILURE = "DETAIL_FAILURE";

export const DETAIL_UPDATE = "DETAIL_UPDATE";
export const DETAIL_UPDATE_SUCCESS = "DETAIL_UPDATE_SUCCESS";
export const DETAIL_UPDATE_FAILURE = "DETAIL_UPDATE_FAILURE";

export const DETAIL_DELETE = "DETAIL_DELETE";
export const DETAIL_DELETE_SUCCESS = "DETAIL_DELETE_SUCCESS";
export const DETAIL_DELETE_FAILURE = "DETAIL_DELETE_FAILURE";

export const RECOMMENT = "RECOMMENT";
export const RECOMMENT_SUCCESS = "RECOMMENT_SUCCESS";
export const RECOMMENT_FAILURE = "RECOMMENT_FAILURE";

export const COMMENT_LIST = "COMMENT_LIST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILURE = "COMMENT_LIST_FAILURE";

export const COMMENT_ADD = "COMMENT_ADD";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAILURE = "COMMENT_ADD_FAILURE";


export const COMMENT_MORE = "COMMENT_MORE";
export const COMMENT_MORE_SUCCESS = "COMMENT_MORE_SUCCESS";
export const COMMENT_MORE_FAILURE = "COMMENT_MORE_FAILURE";

export const COMMENT_REMOVE = "COMMENT_REMOVE";
export const COMMENT_REMOVE_SUCCESS = "COMMENT_REMOVE_SUCCESS";
export const COMMENT_REMOVE_FAILURE = "COMMENT_REMOVE_FAILURE";
